# Generated by Django 3.0.2 on 2020-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientdoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(default='0', max_length=100)),
                ('hpatient', models.CharField(default='0', max_length=100)),
                ('hdoctor', models.CharField(default='0', max_length=100)),
                ('hdate', models.CharField(default='0', max_length=100)),
            ],
            options={
                'db_table': 'patientdoctor',
            },
        ),
    ]
