# Generated by Django 3.0.2 on 2020-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('hcity', models.CharField(max_length=100)),
                ('htreat', models.CharField(max_length=100)),
                ('hbed', models.IntegerField()),
                ('hblood', models.CharField(max_length=100)),
                ('hpatient', models.IntegerField()),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
    ]
