# Generated by Django 3.0.2 on 2020-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='0', max_length=100)),
                ('registration', models.CharField(default='0', max_length=100)),
                ('qualification', models.CharField(default='0', max_length=100)),
                ('speciality', models.CharField(default='0', max_length=100)),
                ('contact', models.CharField(default='0', max_length=100)),
                ('state', models.CharField(default='0', max_length=100)),
                ('city', models.CharField(default='0', max_length=100)),
                ('address', models.CharField(default='0', max_length=100)),
                ('experience', models.CharField(default='0', max_length=100)),
                ('fees', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
    ]
