# Generated by Django 3.0.2 on 2020-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0004_auto_20200507_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappoient',
            name='date',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
