# Generated by Django 3.0.2 on 2020-04-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('blood', models.CharField(max_length=100)),
                ('medical', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bloodbank',
            },
        ),
    ]
