# Generated by Django 3.0.2 on 2020-04-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0002_bloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='age',
            field=models.IntegerField(),
        ),
    ]
