# Generated by Django 3.0.2 on 2020-04-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloodbank', '0003_auto_20200419_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpatient',
            name='age',
            field=models.IntegerField(),
        ),
    ]
